---
driver:
  name: vagrant

provisioner:
    name: chef_zero
    require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - java
      - rbenv::default
      - rbenv::ruby_build
  - name: centos-6.5
   run_list:
      - java
      - rbenv::default
      - rbenv::ruby_build

suites:
  - name: java-buildpack-vm:default
    run_list: 
    attributes:
      java:
        install_flavor: oracle
	    accept_oracle_download_terms: true
	    jdk_version: 7
  }
